### ISSUE TITLE
Class attribute for field doesn't work

### ISSUE THREAD

**Issue by alexboyko** [jadwigo/SimpleForms#14]
If you add `class: long` in configuration of form, it will not be rendered in view, because https://github.com/jadwigo/SimpleForms/blob/master/assets/simpleforms_fields.twig#L28 line filters it out.

**Comment by jadwigo** [comment]
yes class is filtered out 

probably because it would overwrite the class for the element or the container that is set in https://github.com/jadwigo/SimpleForms/blob/master/assets/simpleforms_fields.twig#L4 and https://github.com/jadwigo/SimpleForms/blob/master/assets/simpleforms_fields.twig#L11

i'll have to look into it some more to see what is wrong

**Comment by jadwigo** [comment]
thsi was annoying - sorry
