### ISSUE TITLE
Add class to input control 

### ISSUE THREAD

**Issue by rendler-denis** [jadwigo/SimpleForms#24]
Hello! 

Thanks for the extension, but I did encounter an issue. I'm trying to add Bootstrap to one of the themes I'm using and I do not see a way to add a specific class to the input controls without overriding the templates.
In the docs, the 'class' attribute is said to be used to style the form elements, but in the templates the attribute it is being used to style the container for the input control and the associated label.
Am I missing something?

Thanks,
Denis Rendler

**Comment by jadwigo** [comment]
True, in simpleforms 1.3 the class is added to the container element in the template.

You can copy the template to your theme folder and then override it there without having to mess around in the extension files.

Also be sure to override the simpleforms stylesheet with one of your own, because that will also mess with your layout.

**Comment by philbates35** [comment]
Although copying the template will indeed work, it does seem like a lot of effort for something that IMO is pretty crucial to get a form to match an existing HTML template. Adding both `label_attrs` and `widget_attrs`, allowing you to specify any element attributes you require would be a great addition.

**Comment by jadwigo** [comment]
@philbates35 if it's that crucial, the effort is very minimal.

Try to see it from my point of view: It is either a lot of effort for me te read the mind of everyone who will ever use simpleforms to make it do what all those people want and still make the extension simple ... or a little effort to copy the template to your theme if you want to apply your own styles and structure. Since mind-reading is not in my skill set I built in the latter option.

**Comment by GwendolenLynch** [comment]
@jadwigo I find that :beers: help me reading minds… or maybe I just think it does :wink:
