### ISSUE TITLE
field type 'file' not saving / attaching

### ISSUE THREAD

**Issue by MMelisseOmniboost** [jadwigo/SimpleForms#44]
Hi there,

I've been playing around with the 'file' field type.
It doesn't seem to save to the designated location. Tried absolute paths, relative paths, root folders, /files/ folders... nothing seems to work.
It's also not being sent over along with the e-mail.

storage_location: files/simpleforms_uploads
attach_files: true

Hope you can help.

**Comment by jadwigo** [comment]
are you using simpleforms 2.x?

Because file uploads have been removed from simpleforms since 2.x you need to use boltforms if you want it.

The reasoning behind removing the file uploads was: file uploads are not simple, so they don't belong in the simpleforms extension. And since simpleforms 2.x uses boltforms too you can cut out the middle man and use boltforms for the more complicated forms.

**Comment by MMelisseOmniboost** [comment]
Hi there,

Yeah I figured as much.
Using Boltforms now and it works fine.

Thanks for your reply!
