### ISSUE TITLE
simpleform twig tag breaks ajax calls

### ISSUE THREAD

**Issue by madc** [jadwigo/SimpleForms#45]
Bolt Version: 2.2.14
SimpleForms Version 2.0

Including the `simpleform` twig tag into my `layout.twig` breaks all ajax calls on the page.

``` JSON
{"error":{"type":"Twig_Error_Syntax","message":"Unknown \"simpleform\" function in \"layout.twig\" at line 96.","file":"\/Web\/bolt\/vendor\/twig\/twig\/lib\/Twig\/ExpressionParser.php","line":573}}
```

Any ideas?

**Comment by jadwigo** [comment]
simpleforms is only available in the front-end, not in the back-end or async

if you want to use it in ajax context it will probably not work anyway because the form makes a lot of assumptions about the requests pages it is on.

unfortunately this is unfixable - because we simply don't have the resources to test it in those situations
